# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EyeModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QDialog, QApplication
from PyQt5.uic import loadUi
from Tracking import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Head = QtWidgets.QLabel(self.centralwidget)
        self.Head.setGeometry(QtCore.QRect(230, 10, 691, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Head.sizePolicy().hasHeightForWidth())
        self.Head.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Head.setFont(font)
        self.Head.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Head.setTextFormat(QtCore.Qt.RichText)
        self.Head.setScaledContents(False)
        self.Head.setAlignment(QtCore.Qt.AlignCenter)
        self.Head.setObjectName("Head")
        self.Face = QtWidgets.QLabel(self.centralwidget)
        self.Face.setGeometry(QtCore.QRect(40, 160, 400, 400))
        self.Face.setObjectName("Face")
        self.Left = QtWidgets.QLabel(self.centralwidget)
        self.Left.setGeometry(QtCore.QRect(590, 160, 131, 100))
        self.Left.setObjectName("Left")
        self.Right = QtWidgets.QLabel(self.centralwidget)
        self.Right.setGeometry(QtCore.QRect(830, 160, 131, 100))
        self.Right.setObjectName("Right")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 350, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(594, 420, 461, 231))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 710, 111, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 710, 111, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Head.setText(_translate("MainWindow", "Eye Classification"))
        self.Face.setText(_translate("MainWindow", "TextLabel"))
        self.Left.setText(_translate("MainWindow", "TextLabel"))
        self.Right.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Result"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))

    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        loadUi('EyeModel.ui',self)
        self.logic=0
        self.Start.clicked.connect(self.onClicked)
        self.Stop.clicked.connect(self.close)

    @pyqtSlot()
    def onClicked(self):
        cap=cv2.VideoCapture(0)
        while (cap.isOpened()):
            ret, frame = cap.read()
            if ret == True:
                image_with_faces = faceDetection(frame)
                enlarged_image = cv2.resize(image_with_faces, (400, 400))
                eye_detected_img = eyeDetection(enlarged_image)
            self.displayImage(enlarged_image,1)
            cv2.waitKey()
        cap.release()
        cv2.destroyAllWindows()

    def displayImage(self, img, Face):
        qformat = QImage.Format_Indexed8

        if len(img.shape) == 3:
            if(img.shape[2]) == 4:
                qformat = QImage.Format_RGBA888

            else:
                qformat = QImage.Format_RGBA888
        img = QImage(img, img.shape[1], img.shape[0], qformat)
        img = img.rgbSwapped()
        self.imgForm.setPixmap(QPixmap.fromImage(img))
        self.imgLabel.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)


if __name__ == "__main__":
    import sys

    window = Ui_MainWindow
    window.onClicked()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
